name: igdb
description: IGDB API Wrapper
version: 1.0.0
repository: https://github.com/devsdocs/igdb

environment:
  sdk: ^3.1.0

dependencies:
  dio: ^5.3.2
  igdb_dart_protobuff: ^1.0.1
  reusable_tools: ^1.0.11

dev_dependencies:
  html: ^0.15.4
  lint: ^2.1.2
  test: ^1.21.0
